In [1]:
import pandas as pd
pd.pandas.set_option('display.max_columns', None)
from utils import *

- Loading the DataBase

In [2]:
df = pd.read_csv('BankChurners.csv')

- Dimentions of the DataBase

In [3]:
df.shape

(10127, 23)

- Deleting the last two variables from the database, as it was used only as a transformation made by the database author.

In [4]:
df = df.iloc[:,:-2]

- Checking type of variables and if there are null values present in the database.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CLIENTNUM                 10127 non-null  int64
 1   Attrition_Flag            10127 non-null  object
 2   Customer_Age              10127 non-null  int64
 3   Gender                    10127 non-null  object
 4   Dependent_count           10127 non-null  int64
 5   Education_Level           10127 non-null  object
 6   Marital_Status            10127 non-null  object
 7   Income_Category           10127 non-null  object
 8   Card_Category             10127 non-null  object
 9   Months_on_book            10127 non-null  int64
 10  Total_Relationship_Count  10127 non-null  int64
 11  Months_Inactive_12_mon    10127 non-null  int64
 12  Contacts_Count_12_mon     10127 non-null  int64
 13  Credit_Limit              10127 non-null  float64
 14  Total_Revolving_Bal       10127 non-null  int64
 15  Avg_Open_To_Buy           10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1      10127 non-null  float64
 17  Total_Trans_Amt           10127 non-null  int64
 18  Total_Trans_Ct            10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1       10127 non-null  float64
 20  Avg_Utilization_Ratio     10127 non-null  float64
dtypes: float64(5), int64(10), object(6)
memory usage: 1.6+ MB

As we can see, we have 5 variables of type float, 10 of type integer and 6 of type object, none of the variables have NULL VALUES... We will just do a binary transformation on the Attrition_Flag variable for future correlation calculation.

- Distribution of the dependent variable.

In [6]:
df['Attrition_Flag'].value_counts()

Existing Customer    8500
Attrited Customer    1627
Name: Attrition_Flag, dtype: int64

In [7]:
df_existing = df[df['Attrition_Flag'] == 'Existing Customer']
df_attrited = df[df['Attrition_Flag'] == 'Attrited Customer']

In [8]:
df_existing.describe()

,CLIENTNUM,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
count,8.500000e+03,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000
mean,7.399272e+08,46.262118,2.335412,35.880588,3.914588,2.273765,2.356353,8726.877518,1256.604118,7470.273400,0.772510,4654.655882,68.672588,0.742434,0.296412
std,3.710723e+07,8.081157,1.303229,8.021810,1.528949,1.016741,1.081436,9084.969807,757.745354,9087.671862,0.217783,3512.772635,22.919011,0.228054,0.272568
min,7.080821e+08,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,15.000000,0.256000,816.000000,11.000000,0.028000,0.000000
25%,7.132197e+08,41.000000,1.000000,31.000000,3.000000,1.000000,2.000000,2602.000000,800.000000,1184.500000,0.643000,2384.750000,54.000000,0.617000,0.055000
50%,7.181643e+08,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4643.500000,1364.000000,3469.500000,0.743000,4100.000000,71.000000,0.721000,0.211000
75%,7.783415e+08,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,11252.750000,1807.000000,9978.250000,0.860000,4781.250000,82.000000,0.833000,0.529250
max,8.283431e+08,73.000000,5.000000,56.000000,6.000000,6.000000,5.000000,34516.000000,2517.000000,34516.000000,3.397000,18484.000000,139.000000,3.714000,0.994000

In [9]:
df_attrited.describe()

,CLIENTNUM,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
count,1.627000e+03,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000
mean,7.352614e+08,46.659496,2.402581,36.178242,3.279656,2.693301,2.972342,8136.039459,672.822987,7463.216472,0.694277,3095.025814,44.933620,0.554386,0.162475
std,3.557725e+07,7.665652,1.275010,7.796548,1.577782,0.899623,1.090537,9095.334105,921.385582,9109.208129,0.214924,2308.227629,14.568429,0.226854,0.264458
min,7.080833e+08,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,3.000000,0.000000,510.000000,10.000000,0.000000,0.000000
25%,7.123713e+08,41.000000,2.000000,32.000000,2.000000,2.000000,2.000000,2114.000000,0.000000,1587.000000,0.544500,1903.500000,37.000000,0.400000,0.000000
50%,7.165644e+08,47.000000,2.000000,36.000000,3.000000,3.000000,3.000000,4178.000000,0.000000,3488.000000,0.701000,2329.000000,43.000000,0.531000,0.000000
75%,7.683737e+08,52.000000,3.000000,40.000000,5.000000,3.000000,4.000000,9933.500000,1303.500000,9257.500000,0.856000,2772.000000,51.000000,0.692000,0.231000
max,8.282949e+08,68.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,34516.000000,1.492000,10583.000000,94.000000,2.500000,0.999000

- Distribution of categorical variables according to the categories of the dependent variable.

In [10]:
var_categoricas_cross_tab(df,False)

--------------------------------------------------
Gender
--------------------------------------------------
Gender                F     M
Attrition_Flag
Attrited Customer   930   697
Existing Customer  4428  4072
--------------------------------------------------
Education_Level
--------------------------------------------------
Education_Level    College  Doctorate  Graduate  High School  Post-Graduate  \
Attrition_Flag
Attrited Customer      154         95       487          306             92
Existing Customer      859        356      2641         1707            424

Education_Level    Uneducated  Unknown
Attrition_Flag
Attrited Customer         237      256
Existing Customer        1250     1263
--------------------------------------------------
Marital_Status
--------------------------------------------------
Marital_Status     Divorced  Married  Single  Unknown
Attrition_Flag
Attrited Customer       121      709     668      129
Existing Customer       627     3978    3275      620
--------------------------------------------------
Income_Category
--------------------------------------------------
Income_Category    $120K +  $40K - $60K  $60K - $80K  $80K - $120K  \
Attrition_Flag
Attrited Customer      126          271          189           242
Existing Customer      601         1519         1213          1293

Income_Category    Less than $40K  Unknown
Attrition_Flag
Attrited Customer             612      187
Existing Customer            2949      925
--------------------------------------------------
Card_Category
--------------------------------------------------
Card_Category      Blue  Gold  Platinum  Silver
Attrition_Flag
Attrited Customer  1519    21         5      82
Existing Customer  7917    95        15     473

- Numerical variables that present statistically different distribution when compared with the 'attrited' and 'existing' categories.

In [11]:
var_estat_diferentes = diferenca_estat_entre_var_numericas(df_existing,df_attrited,0.05)

-----------------------------------
CLIENTNUM
Ttest_indResult(statistic=4.677013793086359, pvalue=2.948497995528968e-06)
-----------------------------------
Customer_Age
Ttest_indResult(statistic=-1.8319590211710879, pvalue=0.06698688501759036)
-----------------------------------
Dependent_count
Ttest_indResult(statistic=-1.9112365607100759, pvalue=0.05600239253509299)
-----------------------------------
Months_on_book
Ttest_indResult(statistic=-1.377341848122166, pvalue=0.16843702876495353)
-----------------------------------
Total_Relationship_Count
Ttest_indResult(statistic=15.26672479205373, pvalue=4.829281002184844e-52)
-----------------------------------
Months_Inactive_12_mon
Ttest_indResult(statistic=-15.52128784291336, pvalue=1.0326639995929033e-53)
-----------------------------------
Contacts_Count_12_mon
Ttest_indResult(statistic=-21.02065769896129, pvalue=4.6974896307500795e-96)
-----------------------------------
Credit_Limit
Ttest_indResult(statistic=2.4028585836343748, pvalue=0.016285357205394337)
-----------------------------------
Total_Revolving_Bal
Ttest_indResult(statistic=27.435422507845004, pvalue=6.630148455415696e-160)
-----------------------------------
Avg_Open_To_Buy
Ttest_indResult(statistic=0.028685370654132375, pvalue=0.9771160894458855)
-----------------------------------
Total_Amt_Chng_Q4_Q1
Ttest_indResult(statistic=13.302692876619087, pvalue=4.836642703584486e-40)
-----------------------------------
Total_Trans_Amt
Ttest_indResult(statistic=17.21126707715907, pvalue=1.8574386556609978e-65)
-----------------------------------
Total_Trans_Ct
Ttest_indResult(statistic=40.250735299803345, pvalue=0.0)
-----------------------------------
Total_Ct_Chng_Q4_Q1
Ttest_indResult(statistic=30.49718702151504, pvalue=1.6477247846935747e-195)
-----------------------------------
Avg_Utilization_Ratio
Ttest_indResult(statistic=18.244911490565556, pvalue=3.357689328246027e-73)

- Categorical variables that present categories with statistically different distribution when compared with the 'attrited' and 'existing' categories.

In [12]:
variaveis_categoricas_estat_diferentes(df)

{'Gender': [['F', 'M', 0.0020103200982908155]],
 'Education_Level': [['College', 'Doctorate', 3.269686849186968e-07],
  ['College', 'Graduate', 4.0562977809058605e-05],
  ['College', 'High School', 0.00030118537556626123],
  ['College', 'Post-Graduate', 0.00012401267755143713],
  ['College', 'Uneducated', 0.0001061454899199074],
  ['College', 'Unknown', 8.559919118034437e-06],
  ['Graduate', 'High School', 7.180296461147639e-06],
  ['Graduate', 'Post-Graduate', 2.917884160999009e-05],
  ['Graduate', 'Uneducated', 2.775391434964701e-06],
  ['Graduate', 'Unknown', 4.188651892117818e-08],
  ['High School', 'Post-Graduate', 2.182508607338604e-05],
  ['High School', 'Uneducated', 3.5848280663257307e-06],
  ['High School', 'Unknown', 8.757637351100723e-08],
  ['Post-Graduate', 'Unknown', 0.03596375790051079],
  ['Uneducated', 'Unknown', 1.1926075323580907e-05]],
 'Marital_Status': [['Divorced', 'Married', 0.005282376676671837],
  ['Divorced', 'Single', 0.00011124966957650912],
  ['Divorced', 'Unknown', 0.0017115578443850934],
  ['Married', 'Single', 7.219033075831888e-18],
  ['Married', 'Unknown', 5.91846393716818e-07],
  ['Single', 'Unknown', 0.0004176451571391163]],
 'Income_Category': [['$120K +', '$80K - $120K', 0.038774441181435366],
  ['$120K +', 'Less than $40K', 0.0015772132303093305],
  ['$120K +', 'Unknown', 0.012341202581946955],
  ['$40K - $60K', '$60K - $80K', 0.007642521429754512],
  ['$40K - $60K', '$80K - $120K', 7.5670157745177925e-06],
  ['$40K - $60K', 'Less than $40K', 5.6807275456016076e-11],
  ['$40K - $60K', 'Unknown', 1.6151960135348476e-06],
  ['$60K - $80K', '$80K - $120K', 2.5084294014961327e-08],
  ['$60K - $80K', 'Less than $40K', 6.138843545069724e-14],
  ['$60K - $80K', 'Unknown', 5.867882834362367e-09],
  ['$80K - $120K', 'Less than $40K', 1.8000155426386273e-08],
  ['$80K - $120K', 'Unknown', 3.0497742448785414e-05],
  ['Less than $40K', 'Unknown', 0.00034343061880150324]],
 'Card_Category': [['Blue', 'Gold', 0.04142061957332172],
  ['Blue', 'Silver', 0.02174471289313166]]}

- Variables to be used

In [13]:
columns_to_use = ['Attrition_Flag','Gender','Education_Level','Marital_Status','Income_Category','Card_Category',
'Total_Relationship_Count' , 'Months_Inactive_12_mon', 'Contacts_Count_12_mon', 'Credit_Limit',
'Total_Revolving_Bal', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct', 
'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']

In [14]:
df_final = df[columns_to_use]

In [15]:
df_final.to_csv('BankChurners_dashboard.csv')

### Pre-Processing of variables..

- Binary Categorical Variables

In [16]:
df_final['Attrition_Flag'] = df_final['Attrition_Flag'].apply(lambda x: True if x == 'Existing Customer' else False)

<ipython-input-16-f73d616ac82c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Attrition_Flag'] = df_final['Attrition_Flag'].apply(lambda x: True if x == 'Existing Customer' else False)

In [17]:
df_final['Gender'] = df_final['Gender'].apply(lambda x: 1 if x == 'F' else 0)

<ipython-input-17-afc18763a701>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Gender'] = df_final['Gender'].apply(lambda x: 1 if x == 'F' else 0)

- Ordinal Categorical Variables

In [18]:
scale_mapper = {"Uneducated": 0, "High School": 1, "College": 2,
               "Graduate": 3, "Post-Graduate": 4, "Doctorate": 5, "Unknown": 99}
df_final["Education_Level"] = df_final["Education_Level"].replace(scale_mapper)

<ipython-input-18-9265177d5739>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["Education_Level"] = df_final["Education_Level"].replace(scale_mapper)

In [19]:
scale_mapper1 = {"Less than $40K": 0, "$40K - $60K": 1, "$60K - $80K": 2,
               "$80K - $120K": 3, "$120K +": 4, "Unknown": 99}
df_final["Income_Category"] = df_final["Income_Category"].replace(scale_mapper1)

<ipython-input-19-a4396c80c1a6>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["Income_Category"] = df_final["Income_Category"].replace(scale_mapper1)

- Nominal Categorical Variables

In [20]:
df_final = pd.get_dummies(df_final)

- Correlation to identify multicollinearity

In [21]:
corr = df_final.corr(method='spearman')
corr.style.background_gradient(cmap='coolwarm').set_precision(2)

<ipython-input-21-44599a24aa95>:2: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  corr.style.background_gradient(cmap='coolwarm').set_precision(2)

In [25]:
df_final = df_final.drop('Total_Trans_Ct',axis=1)

In [26]:
df_final.to_csv('BankChurners_modelagem.csv',index=False)